# Generated by Django 6.0.5 on 2026-05-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='preco_aluguel',
            field=models.DecimalField(decimal_places=2, help_text='Preço do aluguel por período (ex: diária).', max_digits=6, verbose_name='Preço do Aluguel'),
        ),
        migrations.CreateModel(
            name='UnidadeBrinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('reservada', 'Reservada'), ('em_locacao', 'Em locacao'), ('higienizacao', 'Higienizacao'), ('manutencao', 'Manutencao'), ('standby', 'Standby'), ('baixada', 'Baixada')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='catalogo.brinquedo', verbose_name='Brinquedo')),
            ],
        ),
    ]
