# Generated by Django 6.0.5 on 2026-05-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_alter_brinquedo_data_cadastro_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brinquedo",
            old_name="disponivel",
            new_name="ativo",
        ),
        migrations.AlterField(
            model_name="brinquedo",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o produto está habilitado para publicação no catálogo; não representa estoque físico disponível.",
                verbose_name="Ativo no catálogo",
            ),
        ),
    ]
