# Generated by Django 6.0.5 on 2026-05-11 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_brinquedo_disponivel_to_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('ordem', 'nome'),
            },
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brinquedos', to='catalogo.categoria', verbose_name='Categoria'),
        ),
    ]
