# Generated by Django 6.0.5 on 2026-05-12 02:30

import catalogo.models
import catalogo.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_categoria_brinquedo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemBrinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=catalogo.models.caminho_imagem_brinquedo, validators=[catalogo.validators.validar_imagem_brinquedo], verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Texto alternativo')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.brinquedo', verbose_name='Brinquedo')),
            ],
            options={
                'verbose_name': 'Imagem do brinquedo',
                'verbose_name_plural': 'Imagens dos brinquedos',
                'ordering': ('-principal', 'ordem', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('brinquedo',), name='catalogo_uma_imagem_principal_por_brinquedo')],
            },
        ),
    ]
