# Generated by Django 6.0.5 on 2026-05-13 03:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_imagembrinquedo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitFesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('preco_aluguel', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preco do aluguel')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no catalogo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Kit festa',
                'verbose_name_plural': 'Kits festa',
                'ordering': ('ordem', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='ItemKitFesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.brinquedo', verbose_name='Brinquedo')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='catalogo.kitfesta', verbose_name='Kit festa')),
            ],
            options={
                'verbose_name': 'Item do kit festa',
                'verbose_name_plural': 'Itens dos kits festa',
                'ordering': ('ordem', 'id'),
                'constraints': [models.UniqueConstraint(fields=('kit', 'brinquedo'), name='catalogo_item_kit_festa_brinquedo_unico')],
            },
        ),
    ]
