# Generated by Django 6.0.5 on 2026-05-14 02:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_kitfesta_itemkitfesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoKitPersonalizavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no catalogo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao')),
                ('preco_base', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preco base')),
                ('quantidade_minima_brinquedos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade minima de brinquedos')),
                ('quantidade_maxima_brinquedos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade maxima de brinquedos')),
                ('modo_elegibilidade', models.CharField(choices=[('categorias', 'Categorias'), ('brinquedos', 'Brinquedos'), ('categorias_e_brinquedos', 'Categorias e brinquedos')], max_length=30, verbose_name='Modo de elegibilidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brinquedos_permitidos', models.ManyToManyField(blank=True, related_name='configuracoes_kits_personalizaveis', to='catalogo.brinquedo', verbose_name='Brinquedos permitidos')),
                ('categorias_permitidas', models.ManyToManyField(blank=True, related_name='configuracoes_kits_personalizaveis', to='catalogo.categoria', verbose_name='Categorias permitidas')),
            ],
            options={
                'verbose_name': 'Configuracao de kit personalizavel',
                'verbose_name_plural': 'Configuracoes de kits personalizaveis',
                'ordering': ('ordem', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='RegraCategoriaKitPersonalizavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_minima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade minima')),
                ('quantidade_maxima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade maxima')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria', verbose_name='Categoria')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_categoria', to='catalogo.configuracaokitpersonalizavel', verbose_name='Configuracao')),
            ],
            options={
                'verbose_name': 'Regra por categoria do kit personalizavel',
                'verbose_name_plural': 'Regras por categoria dos kits personalizaveis',
                'ordering': ('ordem', 'id'),
                'constraints': [models.UniqueConstraint(fields=('configuracao', 'categoria'), name='catalogo_regra_categoria_kit_personalizavel_unica')],
            },
        ),
    ]
