# Generated by Django 6.0.5 on 2026-06-03 21:11

import catalogo.models
import catalogo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_precos_por_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitfesta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=catalogo.models.caminho_imagem_kit_festa, validators=[catalogo.validators.validar_imagem_brinquedo], verbose_name='Imagem'),
        ),
    ]
