# Generated by Django 6.0.5 on 2026-06-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_dedicacao_unidade_kit_e_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='indisponivel_catalogo',
            field=models.BooleanField(default=False, help_text='Mantém o brinquedo visível no catálogo, mas impede sua adição ao carrinho. Não altera o status das unidades físicas.', verbose_name='Marcar como indisponível no catálogo'),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o produto está habilitado para publicação no catálogo; não representa estoque físico disponível.', verbose_name='Exibir no catálogo'),
        ),
    ]
