# Generated by Django 6.0.5 on 2026-07-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_brinquedo_indisponivel_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='indisponivel_catalogo',
            field=models.BooleanField(default=False, help_text='Mantém o brinquedo visível como alugado e impede sua adição ao carrinho. Não altera o status das unidades físicas.', verbose_name='Marcar brinquedo inteiro como alugado'),
        ),
        migrations.AlterField(
            model_name='unidadebrinquedo',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponivel'), ('reservada', 'Reservada'), ('em_locacao', 'Alugado'), ('higienizacao', 'Higienizacao'), ('manutencao', 'Manutencao'), ('standby', 'Standby'), ('baixada', 'Baixada')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
    ]
