# Generated by Django 6.0.5 on 2026-07-03 17:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_alter_brinquedo_indisponivel_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='preco_3_dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preco de 3 dias'),
        ),
    ]
