# Generated by Django 6.0.5 on 2026-07-13 21:43

import catalogo.models
import catalogo.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_brinquedo_preco_3_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitfesta',
            options={'ordering': ('nome', 'id'), 'verbose_name': 'Kit festa', 'verbose_name_plural': 'Kits festa'},
        ),
        migrations.CreateModel(
            name='ImagemKitFesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=catalogo.models.caminho_imagem_kit_festa, validators=[catalogo.validators.validar_imagem_brinquedo], verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Texto alternativo')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.kitfesta', verbose_name='Kit festa')),
            ],
            options={
                'verbose_name': 'Imagem do kit festa',
                'verbose_name_plural': 'Imagens dos kits festa',
                'ordering': ('-principal', 'ordem', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('kit',), name='catalogo_uma_imagem_principal_por_kit_festa')],
            },
        ),
    ]
