# Generated by Django 6.0.5 on 2026-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_alter_brinquedo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='idade_maxima_meses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade maxima recomendada (meses)'),
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='idade_minima_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Use 0 para brinquedos recomendados desde o nascimento.', null=True, verbose_name='Idade minima recomendada (meses)'),
        ),
    ]
