# Generated by Django 6.0.5 on 2026-05-14 03:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0007_configuracaokitpersonalizavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Chave da sessao')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('convertido', 'Convertido'), ('abandonado', 'Abandonado')], db_index=True, default='ativo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrinhos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
                'ordering': ('-atualizado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('brinquedo', 'Brinquedo'), ('kit_festa', 'Kit festa'), ('kit_personalizado', 'Kit personalizado')], max_length=30, verbose_name='Tipo de item')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('nome_snapshot', models.CharField(max_length=200, verbose_name='Nome snapshot')),
                ('preco_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco unitario snapshot')),
                ('subtotal_snapshot', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Subtotal snapshot')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brinquedo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.brinquedo', verbose_name='Brinquedo')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.carrinho', verbose_name='Carrinho')),
                ('configuracao_kit_personalizavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.configuracaokitpersonalizavel', verbose_name='Configuracao de kit personalizavel')),
                ('kit_festa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.kitfesta', verbose_name='Kit festa')),
            ],
            options={
                'verbose_name': 'Item do carrinho',
                'verbose_name_plural': 'Itens do carrinho',
                'ordering': ('criado_em', 'id'),
            },
        ),
    ]
