# Generated by Django 6.0.5 on 2026-05-14 17:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_configuracaokitpersonalizavel_and_more'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key_snapshot', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Chave da sessao snapshot')),
                ('status', models.CharField(choices=[('aguardando_analise', 'Aguardando analise'), ('cancelado', 'Cancelado')], db_index=True, default='aguardando_analise', max_length=30, verbose_name='Status')),
                ('nome_cliente_snapshot', models.CharField(max_length=200, verbose_name='Nome do cliente snapshot')),
                ('telefone_cliente_snapshot', models.CharField(max_length=30, verbose_name='Telefone do cliente snapshot')),
                ('email_cliente_snapshot', models.EmailField(max_length=254, verbose_name='E-mail do cliente snapshot')),
                ('observacoes_cliente', models.TextField(blank=True, verbose_name='Observacoes do cliente')),
                ('data_evento_pretendida', models.DateField(verbose_name='Data pretendida do evento')),
                ('subtotal_itens_snapshot', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Subtotal dos itens snapshot')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('carrinho_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.carrinho', verbose_name='Carrinho de origem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('brinquedo', 'Brinquedo'), ('kit_festa', 'Kit festa'), ('kit_personalizado', 'Kit personalizado')], max_length=30, verbose_name='Tipo de item')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('nome_snapshot', models.CharField(max_length=200, verbose_name='Nome snapshot')),
                ('preco_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco unitario snapshot')),
                ('subtotal_snapshot', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Subtotal snapshot')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('brinquedo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.brinquedo', verbose_name='Brinquedo')),
                ('configuracao_kit_personalizavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.configuracaokitpersonalizavel', verbose_name='Configuracao de kit personalizavel')),
                ('kit_festa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.kitfesta', verbose_name='Kit festa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
                'ordering': ('criado_em', 'id'),
            },
        ),
    ]
