# Generated by Django 6.0.5 on 2026-05-15 04:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='distancia_ida_km_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Distancia de ida em km snapshot'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='distancia_total_km_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Distancia total em km snapshot'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Endereco de entrega snapshot'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='taxa_entrega_retirada_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Taxa de entrega e retirada snapshot'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_estimado_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total estimado snapshot'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_por_km_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Valor por km snapshot'),
        ),
    ]
