# Generated by Django 6.0.5 on 2026-05-15 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_distancia_ida_km_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('versao', models.CharField(max_length=50, unique=True, verbose_name='Versao')),
                ('texto', models.TextField(verbose_name='Texto do contrato')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ('-ativo', '-atualizado_em', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo',), name='pedidos_um_contrato_ativo')],
            },
        ),
        migrations.CreateModel(
            name='AceiteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_versao_snapshot', models.CharField(max_length=50, verbose_name='Versao do contrato snapshot')),
                ('contrato_texto_snapshot', models.TextField(verbose_name='Texto do contrato snapshot')),
                ('nome_cliente_snapshot', models.CharField(max_length=200, verbose_name='Nome do cliente snapshot')),
                ('email_cliente_snapshot', models.EmailField(max_length=254, verbose_name='E-mail do cliente snapshot')),
                ('aceito_em', models.DateTimeField(verbose_name='Aceito em')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-agent')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aceite_contrato', to='pedidos.pedido', verbose_name='Pedido')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='pedidos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Aceite de contrato',
                'verbose_name_plural': 'Aceites de contrato',
                'ordering': ('-aceito_em', '-id'),
            },
        ),
    ]
