# Generated by Django 6.0.5 on 2026-05-15 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_configuracaokitpersonalizavel_and_more'),
        ('pedidos', '0004_contrato_aceitecontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], db_index=True, default='ativa', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_unidades', to='pedidos.itempedido', verbose_name='Item do pedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_unidades', to='pedidos.pedido', verbose_name='Pedido')),
                ('unidade_brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='catalogo.unidadebrinquedo', verbose_name='Unidade do brinquedo')),
            ],
            options={
                'verbose_name': 'Reserva de unidade',
                'verbose_name_plural': 'Reservas de unidades',
                'ordering': ('data_inicio', 'data_fim', 'criado_em'),
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__gt', models.F('data_inicio'))), name='pedidos_reserva_unidade_periodo_valido')],
            },
        ),
    ]
