# Generated by Django 6.0.5 on 2026-05-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_reservaunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_fim_locacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fim da locacao'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_inicio_locacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inicio da locacao'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_analise', 'Aguardando analise'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], db_index=True, default='aguardando_analise', max_length=30, verbose_name='Status'),
        ),
    ]
