# Generated by Django 6.0.5 on 2026-05-16 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_data_fim_locacao_pedido_data_inicio_locacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_analise', 'Aguardando analise'), ('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], db_index=True, default='aguardando_analise', max_length=30, verbose_name='Status'),
        ),
    ]
