# Generated by Django 6.0.5 on 2026-05-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_confirmado_em_pedido_confirmado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_analise', 'Aguardando analise'), ('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('em_locacao', 'Em locacao'), ('retirado', 'Retirado'), ('cancelado', 'Cancelado')], db_index=True, default='aguardando_analise', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservaunidade',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('encerrada', 'Encerrada')], db_index=True, default='ativa', max_length=20, verbose_name='Status'),
        ),
    ]
