# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0009_pedido_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="aceitecontrato",
            name="contrato_titulo_snapshot",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Titulo do contrato snapshot",
            ),
        ),
    ]
