# Generated by Django 6.0.5 on 2026-07-02 17:23

from django.db import migrations, models


def normalizar_snapshots_sem_valor(apps, schema_editor):
    pedido = apps.get_model("pedidos", "Pedido")
    pedido.objects.filter(taxa_entrega_retirada_snapshot__lte=0).update(
        taxa_entrega_retirada_snapshot=None,
        taxa_entrega_status_snapshot="a_confirmar",
    )
    pedido.objects.filter(distancia_ida_km_snapshot__lte=0).update(
        distancia_ida_km_snapshot=None
    )
    pedido.objects.filter(distancia_total_km_snapshot__lte=0).update(
        distancia_total_km_snapshot=None
    )
    pedido.objects.filter(valor_por_km_snapshot__lte=0).update(
        valor_por_km_snapshot=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_remover_session_keys_de_dados_de_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='taxa_entrega_status_snapshot',
            field=models.CharField(choices=[('calculada', 'Calculada'), ('a_confirmar', 'A confirmar'), ('sujeita_analise', 'Sujeita a analise')], default='calculada', max_length=30, verbose_name='Status da taxa de entrega snapshot'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='distancia_ida_km_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Distancia de ida em km snapshot'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='distancia_total_km_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Distancia total em km snapshot'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='taxa_entrega_retirada_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Taxa de entrega e retirada snapshot'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_por_km_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, verbose_name='Valor por km snapshot'),
        ),
        migrations.RunPython(normalizar_snapshots_sem_valor, migrations.RunPython.noop),
    ]
