# Generated by Django 6.0.5 on 2026-05-15 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTaxaEntregaRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_por_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor por km')),
                ('origem_cep', models.CharField(max_length=8, verbose_name='CEP de origem')),
                ('origem_logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('origem_numero', models.CharField(max_length=20, verbose_name='Numero')),
                ('origem_complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('origem_bairro', models.CharField(max_length=120, verbose_name='Bairro')),
                ('origem_cidade', models.CharField(max_length=120, verbose_name='Cidade')),
                ('origem_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('origem_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('origem_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuracao da taxa de entrega e retirada',
                'verbose_name_plural': 'Configuracoes da taxa de entrega e retirada',
                'ordering': ('-ativo', '-atualizado_em', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo',), name='entregas_uma_configuracao_ativa')],
            },
        ),
    ]
