# Generated by Django 6.0.5 on 2026-07-02 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraFreteBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=120, verbose_name='Cidade')),
                ('cidade_normalizada', models.CharField(editable=False, max_length=120)),
                ('bairro', models.CharField(max_length=120, verbose_name='Bairro')),
                ('bairro_normalizado', models.CharField(editable=False, max_length=120)),
                ('valor_taxa', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio ou informe zero para marcar a taxa como a confirmar.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de entrega e retirada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Regra de frete por bairro',
                'verbose_name_plural': 'Regras de frete por bairro',
                'ordering': ('uf', 'cidade_normalizada', 'bairro_normalizado'),
                'constraints': [models.UniqueConstraint(fields=('uf', 'cidade_normalizada', 'bairro_normalizado'), name='entregas_regra_unica_por_bairro')],
            },
        ),
    ]
